kdti/kdti-server

- composer.json
- composer.lock
- config/bundles.php
- config/packages/easy_admin.yaml
- config/packages/security.yaml
- config/packages/test/twig.yaml
- config/packages/test/validator.yaml
- config/packages/translation.yaml
- config/packages/twig.yaml
- config/packages/validator.yaml
- config/routes/easy_admin.yaml
- php/conf.d/php.ini
- php/conf.dev.d/php.dev.ini
- symfony.lock
- templates/base.html.twig
> add easy admin

- src/Controller/Api/JobOfferController.php
- src/Repository/JobOfferRepository.php
- tests/Feature/ListJobOffersTest.php
- tests/Feature/__snapshots__/ListJobOffersTest__test_should_list_only_approved_job_offers.json
- tests/TestCase.php
> [Feat] List all job offers

- Makefile
- config/packages/dev/framework.yaml
- config/packages/easy_admin.yaml
- factories/CompanyFactory.php
- factories/JobOfferFactory.php
- src/Entity/Company.php
- src/Entity/JobOffer.php
- src/Migrations/Version20191124203243.php
- src/Repository/CompanyRepository.php
- tests/Feature/DisplaySingleJobOfferTest.php
- tests/Feature/ListJobOffersTest.php
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/ListJobOffersTest__test_should_list_only_approved_job_offers.json
- tests/Unit/Entity/CompanyTest.php
- tests/Unit/Entity/JobOfferTest.php
> Company admin

- composer.json
- composer.lock
- config/packages/doctrine_extensions.yml
- factories/JobOfferFactory.php
- src/Entity/JobOffer.php
- src/Migrations/Version20191124174004.php
- src/Migrations/Version20191125004104.php
- symfony.lock
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/ListJobOffersTest__test_should_list_only_approved_job_offers.json
- tests/Unit/Entity/JobOfferTest.php
It's a simple implementation for adding slug to the job offer. We can improve it in the future.
Closes #22
> feat: add slug to job offer

- composer.json
- composer.lock
- config/packages/security.yaml
- config/packages/test/security.yml
- src/Controller/Api/CompanyController.php
- src/Controller/BaseController.php
- src/Entity/Company.php
- src/Form/CompanyRegistrationType.php
- src/Repository/CompanyRepository.php
- src/Repository/Contracts/CompanyRepository.php
- src/Request/CompanyRegistration.php
- src/Service/CompanyService.php
- tests/Feature/CompanyRegistrationTest.php
- tests/Feature/__snapshots__/CompanyRegistrationTest__test_company_can_register_itself.json
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/ListJobOffersTest__test_should_list_only_approved_job_offers.json
- tests/Support/PasswordEncoder.php
- tests/Unit/Entity/CompanyTest.php
- tests/Unit/Service/CompanyServiceTest.php
> feat: company registration

- .gitignore
- .php_cs.dist
- Makefile
- composer.json
- composer.lock
- config/packages/security_checker.yaml
- phpcs.xml.dist
- phpinsights.php
- src/Controller/Api/CompanyController.php
- src/Controller/Api/JobOfferController.php
- src/Controller/BaseController.php
- src/Entity/Company.php
- src/Entity/JobOffer.php
- src/Form/CompanyRegistrationType.php
- src/Repository/CompanyRepository.php
- src/Repository/JobOfferRepository.php
- src/Service/CompanyService.php
- symfony.lock
> add phpinsights

- src/Controller/Api/JobOfferController.php
- src/Repository/JobOfferRepository.php
- tests/Feature/DisplaySingleJobOfferTest.php
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_by_slug_a_single_job_offer.json
> add display job offer by slug

- factories/JobOfferFactory.php
- src/Entity/JobOffer.php
- src/Form/PostJobOfferType.php
- src/Migrations/Version20191211013135.php
- src/Request/PostJobOffer.php
- tests/Feature/DisplaySingleJobOfferTest.php
- tests/Feature/ListJobOffersTest.php
- tests/Feature/PostingAJobOfferTest.php
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/ListJobOffersTest__test_should_list_only_approved_job_offers.json
- tests/Feature/__snapshots__/PostingAJobOfferTest__test_a_company_can_post_a_job_offer.json
> add range salary fields

- config/packages/doctrine_extensions.yml
- config/packages/easy_admin/entities/job_offer.yml
- factories/JobOfferFactory.php
- src/Controller/Api/JobOfferController.php
- src/Entity/JobOffer.php
- src/Migrations/Version20191212030607.php
- tests/Feature/DisplaySingleJobOfferTest.php
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_by_slug_a_single_job_offer.json
- tests/Feature/__snapshots__/PostingAJobOfferTest__test_a_company_can_post_a_job_offer.json
> add published at date

- composer.json
- composer.lock
- config/bundles.php
- config/packages/dev/monolog.yaml
- config/packages/prod/monolog.yaml
- config/packages/sentry.yaml
- config/packages/test/monolog.yaml
- symfony.lock
How to log?
e.g:
```php
public function displayBySlug(string $slug, LoggerInterface $logger): Response
{
$logger->error('KDTI test');
```
Sentry print screen
> Adding sentry

- readme.md
Changing Ian Rodrigues contributor github link.
> Fixing contributor name

- config/packages/easy_admin/entities/job_offer.yml
- factories/JobOfferFactory.php
- src/Entity/JobOffer.php
- src/Form/PostJobOfferType.php
- src/Migrations/Version20191213023056.php
- src/Request/PostJobOffer.php
- tests/Feature/DisplaySingleJobOfferTest.php
- tests/Feature/PostingAJobOfferTest.php
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_a_single_job_offer.json
- tests/Feature/__snapshots__/DisplaySingleJobOfferTest__test_display_by_slug_a_single_job_offer.json
- tests/Feature/__snapshots__/PostingAJobOfferTest__test_a_company_can_post_a_job_offer.json
> add allow remote field

- src/Controller/Api/JobOfferController.php
- tests/Feature/PostingAJobOfferTest.php
- tests/Feature/__snapshots__/PostingAJobOfferTest__test_a_company_can_post_two_job_offer.json
> fix circular reference when adding job offer

- src/Entity/JobOffer.php
> allow set published at to expect nullable

- config/packages/dev/monolog.yaml
- config/packages/monolog.yaml
- config/packages/test/monolog.yaml
> Adding sentry on staging

- src/Controller/Api/JobOfferController.php
> Fix find by id

- src/Controller/Api/CompanyController.php
- tests/Feature/ListJobOffersByCompanyTest.php
- tests/Feature/__snapshots__/ListJobOffersByCompanyTest__test_show_jobs_to_company_authenticated.json
> Adding endpoint to get company's job offers

- config/packages/easy_admin/entities/job_offer.yml
> remove html editor

- config/packages/security.yaml
- src/Controller/SecurityController.php
- src/Entity/StaffUser.php
- src/Migrations/Version20200128185751.php
- src/Repository/StaffUserRepository.php
- src/Security/LoginFormAuthenticator.php
- templates/security/login.html.twig
Link: https://symfony.com/blog/new-in-makerbundle-1-8-instant-user-login-form-commands
Generate password
```
docker-compose run php php bin/console security:encode-password
```
after you to create password you need to insert manually on `staff_user` table
Issue #107
> Authentication admin

- composer.json
- composer.lock
- rector.php
> Install rector
